name: "Comelit CLI MQTT Bridge"
description: "Allow owners of a Comelit WiFi intercom system to open the door "
version: "0.0.3"
slug: "comelit_cli_mqtt_bridge"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
discovery:
  - mqtt
services:
  - "mqtt:need"
options:
  comelit_ip_address: null
  comelit_token: null
schema:
  comelit_ip_address: str # match(^([12]?\d{1,2}\.){3}[12]?\d{1,2}$)
  comelit_token: str # password
