test_connection:
  name: Test Connection
  description: Test connection to Comelit device
  fields:
    ip:
      name: IP Address
      description: IP address of the Comelit device
      required: true
      example: "192.168.1.100"
    token:
      name: Token
      description: Authentication token
      required: true
      example: "your_token_here"