name: CI

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort mypy
          
      - name: Lint with ruff
        run: |
          ruff check custom_components/comelit_intercom
          
      - name: Check formatting with black
        run: |
          black --check custom_components/comelit_intercom
          
      - name: Check import order with isort
        run: |
          isort --check-only custom_components/comelit_intercom

  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest Validation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov
          
      # Note: Add actual tests when available
      - name: Test with pytest
        run: |
          echo "No tests yet - skipping"
          # pytest tests/ --cov=custom_components/comelit_intercom