name: HACS Validation

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"  # Daily check for compatibility

jobs:
  validate:
    runs-on: ubuntu-latest
    name: HACS Validation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration